"""Generate the frontend artifacts from the canonical Pydantic schema.

Emits:
  - data/drug-record.schema.json  — the JSON Schema (shareable contract).
  - src/types.generated.ts        — TypeScript interfaces + enum unions.

Python owns the schema (pipeline/schema.py); the TS frontend follows. Run
`tl-gen-types` (or `python -m pipeline.gen_types`) after any schema change.
src/types.ts re-exports from the generated file and adds hand-owned helpers.
"""

from __future__ import annotations

import json
import typing
from pathlib import Path

from pipeline.schema import (
    DrugRecord,
    EndpointRole,
    SourceType,
    TimelineEventType,
)

ROOT = Path(__file__).resolve().parent.parent
SCHEMA_OUT = ROOT / "data" / "drug-record.schema.json"
TS_OUT = ROOT / "src" / "types.generated.ts"

# The root model is authored as DrugRecord but the frontend calls it `Drug`.
_RENAME = {"DrugRecord": "Drug"}

# Named enum aliases, keyed by their frozen value set so enum-typed properties
# resolve to the alias instead of an inline union.
_ENUM_ALIASES = {
    frozenset(typing.get_args(SourceType)): "SourceType",
    frozenset(typing.get_args(EndpointRole)): "EndpointRole",
    frozenset(typing.get_args(TimelineEventType)): "TimelineEventType",
}


def _ts_name(defs_name: str) -> str:
    return _RENAME.get(defs_name, defs_name)


def _resolve(schema: dict) -> str:
    """One property/items schema -> a TypeScript type expression."""
    if "$ref" in schema:
        return _ts_name(schema["$ref"].split("/")[-1])

    if "enum" in schema:
        alias = _ENUM_ALIASES.get(frozenset(schema["enum"]))
        if alias:
            return alias
        return " | ".join(json.dumps(v) for v in schema["enum"])

    if "anyOf" in schema:
        parts = [_resolve(s) for s in schema["anyOf"]]
        seen: list[str] = []
        for p in parts:  # dedup, preserve order (e.g. number|number|null -> number|null)
            if p not in seen:
                seen.append(p)
        return " | ".join(seen)

    t = schema.get("type")
    if t == "array":
        return f"{_resolve(schema['items'])}[]"
    if t in ("integer", "number"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    return "string"


def _interface(name: str, obj: dict) -> str:
    required = set(obj.get("required", []))
    lines = [f"export interface {_ts_name(name)} {{"]
    for prop, sub in obj.get("properties", {}).items():
        optional = "" if prop in required else "?"
        lines.append(f"  {prop}{optional}: {_resolve(sub)};")
    lines.append("}")
    return "\n".join(lines)


def _enum_alias(name: str, values: tuple[str, ...]) -> str:
    body = " | ".join(json.dumps(v) for v in values)
    return f"export type {name} = {body};"


def build_ts(schema: dict) -> str:
    blocks = [
        "// AUTO-GENERATED by pipeline/gen_types.py — DO NOT EDIT.",
        "// Source of truth: pipeline/schema.py. Regenerate with `tl-gen-types`.",
        "// Frontend helpers live in src/types.ts, which re-exports this file.",
        "",
        _enum_alias("SourceType", typing.get_args(SourceType)),
        _enum_alias("EndpointRole", typing.get_args(EndpointRole)),
        _enum_alias("TimelineEventType", typing.get_args(TimelineEventType)),
        "",
    ]
    # Nested defs first, then the root record as `Drug`.
    for def_name, obj in schema.get("$defs", {}).items():
        blocks.append(_interface(def_name, obj))
        blocks.append("")
    blocks.append(_interface(schema.get("title", "DrugRecord"), schema))
    blocks.append("")
    return "\n".join(blocks)


def main() -> None:
    schema = DrugRecord.model_json_schema()
    SCHEMA_OUT.write_text(json.dumps(schema, indent=2) + "\n")
    TS_OUT.write_text(build_ts(schema))
    print(f"[gen-types] wrote {SCHEMA_OUT.relative_to(ROOT)}")
    print(f"[gen-types] wrote {TS_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
