// AUTO-GENERATED by pipeline/gen_types.py — DO NOT EDIT.
// Source of truth: pipeline/schema.py. Regenerate with `tl-gen-types`.
// Frontend helpers live in src/types.ts, which re-exports this file.

export type SourceType = "registry" | "press_release" | "IR" | "journal" | "conference_abstract" | "fda_label" | "drugs_at_fda" | "other";
export type EndpointRole = "primary" | "secondary" | "exploratory";
export type TimelineEventType = "first_in_human" | "phase_start" | "filing" | "accelerated_approval" | "approval" | "data_readout" | "regulatory_event" | "discontinuation";

export interface Discontinuation {
  date: string;
  phase: string;
  reason: string;
}

export interface EfficacyRecord {
  trial: string;
  phase: string;
  endpoint: string;
  value: number | null;
  unit: string;
  role: EndpointRole;
  met: boolean | null;
  sources: Source[];
  comparator?: string | null;
  comparable?: boolean | null;
  definition?: string | null;
  note?: string | null;
}

export interface Identity {
  name: string;
  codes: string[];
  brand_name: string;
  sponsors: string[];
  modality: string;
  target: string;
  indications: string[];
}

export interface Source {
  url: string;
  source_type: SourceType;
}

export interface TimelineEvent {
  date: string | null;
  type: TimelineEventType;
  trial?: string | null;
  confirmed?: boolean | null;
  note: string | null;
  sources: Source[];
}

export interface Trial {
  id: string;
  name: string;
  registry_id: string | null;
  indication: string;
  sponsor: string | string[];
  phases: string[];
  start_date: string | null;
  status: string;
  note: string | null;
  sources: Source[];
}

export interface Verification {
  status: string;
  verified_on?: string | null;
  note?: string | null;
}

export interface Drug {
  id: string;
  identity: Identity;
  trials: Trial[];
  timeline: TimelineEvent[];
  efficacy: EfficacyRecord[];
  discontinuation: Discontinuation | null;
  _verification?: Verification | null;
}
